spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/anveshdheeti/configuration_properties.git
          clone-on-start: true
mangagement:
   security:
    disable: false